### ISSUE TITLE
e

### ISSUE THREAD

**Issue by gtxykn0504** [MarcusYYDS/home-web#1]

**Comment by gtxykn0504** [comment]
抱歉抱歉，看错了

**Comment by Marcus-zh** [comment]
> 抱歉抱歉，看错了

我根目录有个之前的html忘删了，删一下谢谢（）

**Comment by Marcus-zh** [comment]
> 抱歉抱歉，看错了

还有就是希望保留下页脚的theme

**Comment by gtxykn0504** [comment]
hello，该版本的home-web我已经没有再使用了，稍后将删除fork。有个问题就在手机端的适配太差了，文字无法正常显示（这也是为什么删除了页脚的theme，有时候页脚的theme会“挤压”到不该去的地方）
